base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  wait_timeout: 600
  pool: 25
  username: root
  password: kenrome001
  host: localhost
  port: 3306

development:
  <<: *base
  database: six_five

test:
  <<: *base
  database: six_five
production:
  <<: *base
  database: six_five
