base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  wait_timeout: 600
  pool: 250
  username: root
  password: kenrome001
  host: 127.0.0.1
  port: 3307

development:
  <<: *base
  database: six_five

test:
  <<: *base
  database: six_five
production:
  <<: *base
  database: six_five
